package newYearGift.controller.other;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import newYearGift.logger.LoggerContainer;
import org.slf4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class CheckErrorMessageSendingOnMailController {

    @FXML
    private Label notificationLabel;

    private final Logger logger;

    @Autowired
    public CheckErrorMessageSendingOnMailController(
            LoggerContainer loggerContainer
    ) {
        this.logger = loggerContainer.getLogger();
    }

    @FXML
    private void sendTestErrorMessage() {
        logger.error("Test error message generated by CheckErrorMessageSendingOnMailController");
        notificationLabel.setText("Check your mail!");
    }

}
