CREATE TABLE candy
(
		id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		name                     VARCHAR(50)  NOT NULL,
		trademark                VARCHAR(100) NOT NULL,
		type                     VARCHAR(255) NOT NULL CHECK (type IN (
			   'Chocolate', 'Caramel', 'Gummies', 'Lollipop', 'Toffee', 'Fudge', 'Wafer'
		)),
		weight                   INTEGER,
		calories                 INTEGER,
		fats                     DECIMAL(5, 2),
		proteins                 DECIMAL(5, 2),
		carbohydrates            DECIMAL(5, 2),
		sugar                    DECIMAL(5, 2),
		CONSTRAINT pk_candy PRIMARY KEY (id)
);

CREATE TABLE gift
(
		id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
		name        VARCHAR(100) NOT NULL,
		description VARCHAR(1000),
		CONSTRAINT pk_gift PRIMARY KEY (id)
);

CREATE TABLE gift_candy_weights
(
		gift_id      BIGINT NOT NULL,
		weight_in_grams INTEGER,
		candy_id     BIGINT NOT NULL,
		CONSTRAINT pk_gift_candy_weights PRIMARY KEY (gift_id, candy_id)
);

ALTER TABLE gift_candy_weights
		ADD CONSTRAINT fk_gift_candy_weights_on_candy FOREIGN KEY (candy_id) REFERENCES candy (id);

ALTER TABLE gift_candy_weights
		ADD CONSTRAINT fk_gift_candy_weights_on_gift FOREIGN KEY (gift_id) REFERENCES gift (id);