
ALTER TABLE gift
		ADD COLUMN author VARCHAR(30) NOT NULL default 'Admin',
		ADD COLUMN creation_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE gift
		ALTER COLUMN name TYPE VARCHAR(30);

ALTER TABLE gift
		ALTER COLUMN description TYPE VARCHAR(200);